### ISSUE TITLE
viewdemo crash

### ISSUE THREAD

**Issue by sobakaruzhaya** [ScriptedSnark/agmod-client-updated#7]
[crash-2022-06-07-17-08-12.txt](https://github.com/ScriptedSnark/agmod-client-updated/files/8853030/crash-2022-06-07-17-08-12.txt)
https://disk.yandex.ru/d/elaa1viqjJkscw

**Comment by L09k0** [comment]
это и за читов всё

**Comment by ScriptedSnark** [comment]
Это база)

**Comment by sobakaruzhaya** [comment]
кстати, демки некоторые не до конца пишутся)

**Comment by ScriptedSnark** [comment]
Fixed in https://github.com/ScriptedSnark/agmod-client-updated/commit/bb26c1ce300dcf352c5e7a1c63f43809ccded4f4.
