### ISSUE TITLE
Scoreboard crash

### ISSUE THREAD

**Issue by 7Noghost7** [ScriptedSnark/agmod-client-updated#8]
crashed while scoreboard was opened and some player left from server
[crash-2022-06-07-22-19-03.txt](https://github.com/ScriptedSnark/agmod-client-updated/files/8855978/crash-2022-06-07-22-19-03.txt)
[crash-2022-06-07-22-19-03.zip](https://github.com/ScriptedSnark/agmod-client-updated/files/8855984/crash-2022-06-07-22-19-03.zip)

**Comment by ScriptedSnark** [comment]
Checked stack trace.

Seems like duplicate of #6.

**Comment by ScriptedSnark** [comment]
Checked stack trace.

Seems like duplicate of #6.

**Comment by ScriptedSnark** [comment]
Fixed.
